@ToDoList_HostAddress = http://localhost:8080

GET {{ToDoList_HostAddress}}/todoList/
Accept: application/json

POST {{ToDoList_HostAddress}}/todoList/
Accept: application/json

DELETE {{ToDoList_HostAddress}}/todoList/:id
Accept: application/json

PUT {{ToDoList_HostAddress}}/todoList/

###
